</div>
</div><!-- end container -->
</div><!-- end main-wrap -->

<div id="footer-wrap">
	<div class="container">
		<div id="footer-divide"></div>
		<div class='wsite-elements wsite-footer'>
			<div class="paragraph" style="text-align:right;"><span style="color:rgb(153, 153, 153); font-weight:200"><span style="color:rgb(153, 153, 153); font-weight:200">&copy; Jamie Zvirzdin 2018. All Rights Reserved</span></span></div></div>
		<script type='text/javascript'>
            //<!--

            if (document.cookie.match(/(^|;)\s*is_mobile=1/)) {
                var windowHref = window.location.href || '';
                if (windowHref.indexOf('?') > -1) {
                    windowHref += '&';
                } else {
                    windowHref += '?';
                }
                document.write(
                    "&nbsp;&nbsp;&nbsp;&nbsp;" +
                    "<a class='wsite-view-link-mobile' href='" + windowHref + "view=mobile'>Mobile Site</a>"
                );
            }

            //-->
		</script>
	</div><!-- end container -->
</div><!-- end footer-wrap -->
<div id="customer-accounts-app"></div>
<!--<script src="//cdn2.editmysite.com/js/site/main-customer-accounts-site.js?buildTime=1574724498"></script>-->
</body>
</html>
