<!DOCTYPE html>
<html lang="en">
<head><script src="http://www.jamiezvirzdin.com/gdpr/gdprscript.js?buildTime=1575591387&hasRemindMe=true&stealth=false"></script>
	<title>Jamie Zvirzdin - Bio</title><meta property="og:site_name" content="Jamie Zvirzdin" />
	<meta property="og:title" content="Jamie Zvirzdin" />
	<meta property="og:description" content="Website of Jamie Zvirzdin, author." />
	<meta property="og:image" content="http://www.jamiezvirzdin.com/uploads/3/8/4/2/3842486/published/4671688.jpg?1535750645" />
	<meta property="og:image" content="http://www.jamiezvirzdin.com/uploads/3/8/4/2/3842486/screenshot-2019-09-26-12-39-37_1_orig.png" />
	<meta property="og:image" content="http://www.jamiezvirzdin.com/uploads/3/8/4/2/3842486/published/npr-2019.jpeg?1569511870" />
	<meta property="og:image" content="http://www.jamiezvirzdin.com/uploads/3/8/4/2/3842486/published/nasa.jpeg?1569511889" />
	<meta property="og:image" content="http://www.jamiezvirzdin.com/uploads/3/8/4/2/3842486/published/img-20190926-111203883.jpg?1569510932" />
	<meta property="og:image" content="http://www.jamiezvirzdin.com/uploads/3/8/4/2/3842486/published/screen-shot-2019-04-19-at-6-25-08-pm.png?1569511884" />
	<meta property="og:image" content="http://www.jamiezvirzdin.com/uploads/3/8/4/2/3842486/published/cosray-4-2-19.jpg?1555714016" />
	<meta property="og:image" content="http://www.jamiezvirzdin.com/uploads/3/8/4/2/3842486/published/aaas-2019.jpg?1555713984" />
	<meta property="og:image" content="http://www.jamiezvirzdin.com/uploads/3/8/4/2/3842486/editor/screenshot-2019-02-14-01-15-12_2.png?1550376685" />
	<meta property="og:image" content="http://www.jamiezvirzdin.com/uploads/3/8/4/2/3842486/published/img-20181122-154217412.jpg?1550125700" />
	<meta property="og:url" content="http://www.jamiezvirzdin.com/" />

	<meta name="description" content="Website of Jamie Zvirzdin, author." />
	<meta name="keywords" content="author, Jamie Zvirzdin, writing, writer, experimental fiction, blog, Jamie, Zvirzdin" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<link id="wsite-base-style" rel="stylesheet" type="text/css" href="//cdn2.editmysite.com/css/sites.css?buildTime=1574724498" />
	<link rel="stylesheet" type="text/css" href="//cdn2.editmysite.com/css/old/fancybox.css?1574724498" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="http://www.jamiezvirzdin.com/files/main_style.css?1575225489" title="wsite-theme-css" />
	<link href='//fonts.googleapis.com/css?family=Titillium+Web:400,300,300italic,200,200italic,700,400italic,700italic&subset=latin,latin-ext' rel='stylesheet' type='text/css' />
	<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,700,400italic,700italic&subset=latin,latin-ext' rel='stylesheet' type='text/css' />


	<link href='//fonts.googleapis.com/css?family=Cardo:400,700,400italic&subset=latin,latin-ext' rel='stylesheet' type='text/css' />
	<style type='text/css'>
		.wsite-elements.wsite-not-footer:not(.wsite-header-elements) div.paragraph, .wsite-elements.wsite-not-footer:not(.wsite-header-elements) p, .wsite-elements.wsite-not-footer:not(.wsite-header-elements) .product-block .product-title, .wsite-elements.wsite-not-footer:not(.wsite-header-elements) .product-description, .wsite-elements.wsite-not-footer:not(.wsite-header-elements) .wsite-form-field label, .wsite-elements.wsite-not-footer:not(.wsite-header-elements) .wsite-form-field label, #wsite-content div.paragraph, #wsite-content p, #wsite-content .product-block .product-title, #wsite-content .product-description, #wsite-content .wsite-form-field label, #wsite-content .wsite-form-field label, .blog-sidebar div.paragraph, .blog-sidebar p, .blog-sidebar .wsite-form-field label, .blog-sidebar .wsite-form-field label {font-family:"Cardo" !important;}
		#wsite-content div.paragraph, #wsite-content p, #wsite-content .product-block .product-title, #wsite-content .product-description, #wsite-content .wsite-form-field label, #wsite-content .wsite-form-field label, .blog-sidebar div.paragraph, .blog-sidebar p, .blog-sidebar .wsite-form-field label, .blog-sidebar .wsite-form-field label {}
		.wsite-elements.wsite-footer div.paragraph, .wsite-elements.wsite-footer p, .wsite-elements.wsite-footer .product-block .product-title, .wsite-elements.wsite-footer .product-description, .wsite-elements.wsite-footer .wsite-form-field label, .wsite-elements.wsite-footer .wsite-form-field label{}
		.wsite-elements.wsite-not-footer:not(.wsite-header-elements) h2, .wsite-elements.wsite-not-footer:not(.wsite-header-elements) .product-long .product-title, .wsite-elements.wsite-not-footer:not(.wsite-header-elements) .product-large .product-title, .wsite-elements.wsite-not-footer:not(.wsite-header-elements) .product-small .product-title, #wsite-content h2, #wsite-content .product-long .product-title, #wsite-content .product-large .product-title, #wsite-content .product-small .product-title, .blog-sidebar h2 {font-weight:700 !important;}
		#wsite-content h2, #wsite-content .product-long .product-title, #wsite-content .product-large .product-title, #wsite-content .product-small .product-title, .blog-sidebar h2 {color:#2a2a2a !important;}
		.wsite-elements.wsite-footer h2, .wsite-elements.wsite-footer .product-long .product-title, .wsite-elements.wsite-footer .product-large .product-title, .wsite-elements.wsite-footer .product-small .product-title{}
		#wsite-title {}
		.wsite-menu-default a {}
		.wsite-menu a {}
		.wsite-image div, .wsite-caption {}
		.galleryCaptionInnerText {}
		.fancybox-title {}
		.wslide-caption-text {}
		.wsite-phone {}
		.wsite-headline,.wsite-header-section .wsite-content-title {}
		.wsite-headline-paragraph,.wsite-header-section .paragraph {}
		.wsite-button-inner {}
		.wsite-not-footer blockquote {}
		.wsite-footer blockquote {}
		.blog-header h2 a {}
		#wsite-content h2.wsite-product-title {}
		.wsite-product .wsite-product-price a {}
		@media screen and (min-width: 767px) {.wsite-elements.wsite-not-footer:not(.wsite-header-elements) div.paragraph, .wsite-elements.wsite-not-footer:not(.wsite-header-elements) p, .wsite-elements.wsite-not-footer:not(.wsite-header-elements) .product-block .product-title, .wsite-elements.wsite-not-footer:not(.wsite-header-elements) .product-description, .wsite-elements.wsite-not-footer:not(.wsite-header-elements) .wsite-form-field label, .wsite-elements.wsite-not-footer:not(.wsite-header-elements) .wsite-form-field label, #wsite-content div.paragraph, #wsite-content p, #wsite-content .product-block .product-title, #wsite-content .product-description, #wsite-content .wsite-form-field label, #wsite-content .wsite-form-field label, .blog-sidebar div.paragraph, .blog-sidebar p, .blog-sidebar .wsite-form-field label, .blog-sidebar .wsite-form-field label {font-size:19px !important;line-height:28px !important;}
			#wsite-content div.paragraph, #wsite-content p, #wsite-content .product-block .product-title, #wsite-content .product-description, #wsite-content .wsite-form-field label, #wsite-content .wsite-form-field label, .blog-sidebar div.paragraph, .blog-sidebar p, .blog-sidebar .wsite-form-field label, .blog-sidebar .wsite-form-field label {}
			.wsite-elements.wsite-footer div.paragraph, .wsite-elements.wsite-footer p, .wsite-elements.wsite-footer .product-block .product-title, .wsite-elements.wsite-footer .product-description, .wsite-elements.wsite-footer .wsite-form-field label, .wsite-elements.wsite-footer .wsite-form-field label{}
			.wsite-elements.wsite-not-footer:not(.wsite-header-elements) h2, .wsite-elements.wsite-not-footer:not(.wsite-header-elements) .product-long .product-title, .wsite-elements.wsite-not-footer:not(.wsite-header-elements) .product-large .product-title, .wsite-elements.wsite-not-footer:not(.wsite-header-elements) .product-small .product-title, #wsite-content h2, #wsite-content .product-long .product-title, #wsite-content .product-large .product-title, #wsite-content .product-small .product-title, .blog-sidebar h2 {font-size:28px !important;}
			#wsite-content h2, #wsite-content .product-long .product-title, #wsite-content .product-large .product-title, #wsite-content .product-small .product-title, .blog-sidebar h2 {}
			.wsite-elements.wsite-footer h2, .wsite-elements.wsite-footer .product-long .product-title, .wsite-elements.wsite-footer .product-large .product-title, .wsite-elements.wsite-footer .product-small .product-title{}
			#wsite-title {}
			.wsite-menu-default a {}
			.wsite-menu a {}
			.wsite-image div, .wsite-caption {}
			.galleryCaptionInnerText {}
			.fancybox-title {}
			.wslide-caption-text {}
			.wsite-phone {}
			.wsite-headline,.wsite-header-section .wsite-content-title {}
			.wsite-headline-paragraph,.wsite-header-section .paragraph {}
			.wsite-button-inner {}
			.wsite-not-footer blockquote {}
			.wsite-footer blockquote {}
			.blog-header h2 a {}
			#wsite-content h2.wsite-product-title {}
			.wsite-product .wsite-product-price a {}
            #footer-wrap .container {
                max-width: 980px;
                width: inherit;
            }
            #wsite-header-search-form .wsite-search-input { box-sizing: unset; }
		}</style>
	<script>
        var STATIC_BASE = '//cdn1.editmysite.com/';
        var ASSETS_BASE = '//cdn2.editmysite.com/';
        var STYLE_PREFIX = 'wsite';
	</script>
	<script
		src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
		integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8="
		crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body class="tall-header-page wsite-theme-light wsite-background  wsite-page-index"><div id="header-wrap">
	<div class="container">
		<table id="header">
			<tr>
				<td class="phone-number"><span class="wsite-text wsite-phone">
	Thanks for visiting.
</span></td>
				<td id="header-right">
					<table>
						<tr>
							<td class="social"><div style="text-align:left;"><div style="height:0;overflow:hidden"></div>
									<span class="wsite-social wsite-social-default"></span>
									<div style="height:0;overflow:hidden"></div></div></td>
							<td class="search">
                                <span class="wsite-search">
                                    <form id="wsite-header-search-form" action="http://www.jamiezvirzdin.com/apps/search" method="get">
                                        <input title="search" type="text" name="q" class="wsite-search-input" autocomplete="off" placeholder="Search"/><span class="wsite-search-button"><span class="wsite-search-button-inner"></span></span>
                                    </form>
                                </span>
                            </td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</div><!-- end container -->

	<div id="nav-wrap">
		<div class="container">
			<table>
				<tr>
					<td id="logo"><span class="wsite-logo">

	<a href="http://www.jamiezvirzdin.com">

	<span id="wsite-title">Jamie Zvirzdin</span>

	</a>

</span></td>
					<td id="nav"><ul class="wsite-menu-default">
							<li class="wsite-menu-item-wrap">
								<a
									href="http://www.jamiezvirzdin.com"
									class="wsite-menu-item"
								>
									Bio
								</a>

							</li>
							<li id="pg540457871753125312" class="wsite-menu-item-wrap">
								<a
									href="http://www.jamiezvirzdin.com/publications.html"
									class="wsite-menu-item"
								>
									Publications
								</a>

							</li>
							<li id="pg487350607504914038" class="wsite-menu-item-wrap">
								<a
									href="http://www.jamiezvirzdin.com/fresh-courage-take.html"
									class="wsite-menu-item"
								>
									Fresh Courage Take
								</a>

							</li>
							<li id="pg618266316325633485" class="wsite-menu-item-wrap">
								<a
									href="http://www.jamiezvirzdin.com/contact.html"
									class="wsite-menu-item"
								>
									Contact
								</a>

							</li>
						</ul>
					</td>
				</tr>
			</table>
		</div><!-- end container -->
	</div><!-- end nav-wrap -->
</div><!-- end header-wrap -->


<div id="main-wrap">
	<div class="container">
		<div id="wsite-content" class="wsite-elements wsite-not-footer">